"""'Init'

Revision ID: 589e39976567
Revises: 
Create Date: 2022-12-16 00:37:07.796413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589e39976567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
